config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  resources :lists, only: [:index, :new, :show, :create] do
    resources :bookmarks, only: [:create, :new]
  end

  resources :bookmarks, only: [:destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/bookmark.rb
class Bookmark < ApplicationRecord
  belongs_to :movie
  belongs_to :list

  validates :comment, length: { minimum: 6 }
  validates :movie_id, uniqueness: { scope: :list_id }
end

app/models/list.rb
class List < ApplicationRecord
  has_many :bookmarks, dependent: :destroy
  has_many :movies, through: :bookmarks

  validates :name, uniqueness: true
  validates :name, presence: true
end

app/models/movie.rb
class Movie < ApplicationRecord
  has_many :bookmarks

  validates :title, uniqueness: true
  validates :overview, uniqueness: true
  validates :title, presence: true
  validates :overview, presence: true

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bookmarks_controller.rb
class BookmarksController < ApplicationController
  before_action :set_list

  def new
    # we need to know what the list id is - you don't need the movie id because that is being handled by the simple form association
    @bookmark = Bookmark.new
  end

  def create
    @bookmark = Bookmark.new(bookmark_params)
    @bookmark.list = @list
    @bookmark.save
    redirect_to list_path(@list)
  end

  def destroy
    @bookmark = Bookmark.find(params[:id])
    @bookmark.destroy
    redirect_to list_path(@list), status: :see_other
  end

  private

  def set_list
    @list = List.find(params[:list_id])
  end

  def bookmark_params
    params.require(:bookmark).permit(:movie_id, :comment)
  end
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  def index
    @lists = List.all
  end

  def new
    @list = List.new
  end

  def create
    @list = List.new(list_params)
    @list.save
    redirect_to lists_path
  end

  def show
    @list = List.find(params[:id])
  end

  private

  def list_params
    params.require(:list).permit(:name)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookmarks_helper.rb
module BookmarksHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/views/bookmarks/new.html.erb
<div class="container">
  <h1>Create a New Bookmark</h1>
  <%= simple_form_for [@list, @bookmark] do |f| %>
    <%= f.association :movie %>
    <%= f.input :comment %>
    <%= f.button :submit %>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsWatchList</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/lists/index.html.erb
<div class="container">
  <h1>Your Movie Lists</h1>
  <div class="row">
    <div class="col-sm-6">
      <div class="card">
        <% @lists.each do |list| %>
          <div class="card-body">
            <h5 class="card-title"><%= list.name %></h5>
            <p class="card-text">With supporting text below as a natural lead-in to additional content.</p>
            <%# you can use an a tag - with interpolation %>
            <%= link_to "More Info...", list_path(list) %>
          </div>
        <% end %>
      </div>
    </div>
  </div>

  <%= link_to 'Add a new list', new_list_path %>
</div>

app/views/lists/new.html.erb
<div class="container">
  <h1>Add a New List</h1>
  <%= form_with model: @list do |f| %>
    <%= f.label :name %>
    <%= f.text_field :name %>
    <%= f.submit%>
  <% end %>

  <%= link_to "Back to lists", lists_path %>
</div>

app/views/lists/show.html.erb
<div class="container">
  <h1><%= @list.name %></h1>
  <% @list.movies.each do |movie| %>
    <div class="card" style="width: 18rem;">
      <img src="<%= movie.poster_url %>" class="card-img-top" alt="...">
      <div class="card-body">
        <h5 class="card-title"><%= movie.title %></h5>
        <p class="card-text"><%= movie.overview %></p>
        <% bookmark = Bookmark.find_by(params[list: @list, movie: movie]) %>
        <%= link_to "Destroy", bookmarks_path(bookmark), data: { turbo_method: :delete, turbo_confirm: "Are you sure?" } %>
      </div>
    </div>
  <% end %>
</div>